# Generated by Django 5.2 on 2025-05-17 05:48

import courses.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseimage',
            name='image',
        ),
        migrations.AddField(
            model_name='courseimage',
            name='video_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/', validators=[courses.validators.validate_video_file_extension]),
            preserve_default=False,
        ),
    ]
