# Generated by Django 5.2 on 2025-04-07 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_courseimage_image_courseimage_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CourseImage',
        ),
    ]
