# Generated by Django 5.2 on 2025-04-07 01:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_video_file_courseimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseimage',
            name='video_file',
        ),
        migrations.AddField(
            model_name='courseimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
