# Generated by Django 5.2 on 2025-04-07 18:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_courseimage_video_file_courseimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
