# Generated by Django 5.2 on 2025-05-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='user',
            new_name='Email',
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together=set(),
        ),
    ]
